services:
  # Servicio para la base de datos PostgreSQL
  postgres-db:
    image: postgres:16-alpine
    container_name: wallet-postgres-db
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio para la API de Spring Boot
  wallet-api:
    build: .
    container_name: wallet-core-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/wallet_db
      SPRING_DATASOURCE_USERNAME: wallet_user
      SPRING_DATASOURCE_PASSWORD: wallet_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data: